# Results comparison for MIST with final models of model B

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path_default = pre_path + "results/model_B/default_models"
path_fine_tuned = pre_path + "results/model_B/fine_tuned_models"
path_final = pre_path + "results/model_B/final_models"

## Final model results

In [4]:
compare_metrics(path_final, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["KNN"],
                data_filters=["scale_quantile"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff              3.345 - 5.379  0.977
                                    log_g             -1.016 - 6.258  0.881
                                    radius             -0.997 - 3.13  0.919

                                                       RMSE    MAE  MedAE  \
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff             0.052  0.015  0.002
                                    log_g             0.420  0.134  0.007
                                    radius            0.210  0.068  0.005

                                                       CORR  MAX_ER  \
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff             0.989   0.910
                                    log_g             0.939   5.477
                                    radius            0.959   2.741

                                                                                            Percentiles  \
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff             75 : 0.007 / 90 : 0.036 / 95 : 0.075 / 99 : 0.246
                                    log_g              75 : 0.032 / 90 : 0.363 / 95 : 0.943 / 99 : 1.98
                                    radius            75 : 0.019 / 90 : 0.182 / 95 : 0.471 / 99 : 0.991

                                                       time
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff             1.087
                                    log_g             1.087
                                    radius            1.087

In [5]:
compare_metrics(path_final, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["scale_quantile"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff              3.345 - 5.379
                                            log_g             -1.016 - 6.258
                                            radius             -0.997 - 3.13

                                                                RVE   RMSE  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff             0.977  0.052
                                            log_g             0.876  0.429
                                            radius            0.916  0.215

                                                                MAE  MedAE  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff             0.016  0.003
                                            log_g             0.142  0.014
                                            radius            0.072  0.008

                                                               CORR  MAX_ER  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff             0.989   0.882
                                            log_g             0.936   5.260
                                            radius            0.957   2.632

                                                                                                    Percentiles  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff              75 : 0.01 / 90 : 0.036 / 95 : 0.077 / 99 : 0.239
                                            log_g               75 : 0.05 / 90 : 0.35 / 95 : 0.948 / 99 : 2.065
                                            radius            75 : 0.026 / 90 : 0.175 / 95 : 0.474 / 99 : 1.033

                                                                time
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff             22.296
                                            log_g             22.296
                                            radius            22.296